<?php

/**
 * Converts a "program_type" taxonomy term to it's ID.
 *
 * @param string $name
 *   Name of the taxonomy term.
 *
 * @return int
 *   ID of the relevant taxonomy term.
 */
function _c11n_migrate_process_program_type($name) {

  $name = trim($name);

  // See if the term exists.
  $term_coll = entity_load_multiple_by_properties('taxonomy_term', array(
    'vid' => 'program_types',
    'name' => $name,
  ));

  // If the term already exists, we don't have to create it.
  if (count($term_coll)) {
    $term = reset($term_coll);
  }
  // If if does not exist, create it so that we can return it's ID.
  else {
    $term = entity_create('taxonomy_term', [
      'vid' => 'program_types',
      'name' => $name,
    ]);
    $term->save();
  }

  // Return the ID of the term for use in migration.
  return $term->id();

}
